version: '3'

services:
    nodejs:
         build:
           context: .
         container_name: nodejsserver
         ports:
           - '3000:3000'
         networks:
           - example-net 
    nginx:
         build:
           context: ./nginx
         container_name: nginxserver
         ports:
           - '88:80'
         depends_on:
           - nodejs
         networks:
           - example-net

networks:
  example-net:
     external: true
