version: '3'

services:
    nodejs:
         build:
           context: ./myapp
         container_name: nodejsser
         ports:
           - '3333:3000'
         networks:
           - example-net 
    nginx:
     build:
       context: ./nginx
     container_name: nginxser
     ports:
           - '85:80'
     depends_on:
           - nodejs
     networks:
           - example-net

networks:
  example-net:
     external: true
