version: '3'

services:
    nodejs:
         build:
           context: /root/jsapp
         container_name: nodejsserver
         ports:
           - '3333:3000'
         networks:
           - example-net 
    nginx:
     build:
       context: /root/jsapp/nginx
     container_name: nginxserver
     ports:
           - '85:80'
     depends_on:
           - nodejs
     networks:
           - example-net

networks:
  example-net:
     external: true
